#Proof of Concept for Jigsaw Build Decoration

I wanted to create a way to track meta data using Blade directives rather than do some crazy YAML front matter parsing or something similar.  The idea would be to put you meta data into a Blade directive thaat would then collect the meta data as well as make it available for use within the Blade file.  After the initial build is complete, all meta data would be collected and could then be used to "decorate" the build by providing the ability to index the collection, create rss feeds, archive links, etc.  The question became, how do I decorate the build?  The best answer I came up with was to "reprocess" the build as if it were still Blade files.  This gives you the ability to place your "decorations" with `@verbatim` tags.  After the initial build, the `@verbatim` tags are removed and your second layer of Blade directives is exposed.  Iterative or recursive Blade compilation.  How cool is that?

There were a couple of challenges to overcome.  I didn't want to change the way regular Blade files were handled, so I needed another file handler that could handle those Blade files that were needed to be processed more than once.  Then I had to keep track of what files were being decorated so I would what to name the file once the handler was complete, i.e. does this get turned into a pretty url, or does this need to wait around to get reprocessed again.

The changes to Jigsaw are basically three-fold.
1. Setup a plugin system that exposes key parts of the application like file handling and blade compilation and allows the user to make substitutions and/or extensions to the functionality.
2. Add the ability to decorate a build iteratively.
3. Create a plugin to collect meta data from blade files and decorate the build with information gathered in the collection.

Step 1 basically moves the container object used by the build closer to center stage.  The container becomes the `Puzzle Box`, an extension of the `Container` class, that will register these plugins, called `Puzzle Pieces`, and tag them for use in the main Jigsaw instance.  It also reworks the file handlers into `Puzzle Pieces`.

Step 2 gets a little complicated.  Jigsaw will create an initial build and store it in the normal destination.  If there are any Build Decorators (special kinds of Puzzle Pieces), then it will iterate through them, providing each of them with some information and hitting a `decorate` method on them to give them an opportunity to do cool stuff.  Then it will re-build the site again using the prior build result.  Repeat until finished!

Step 3 is where all the fun is.  Turns out I didn't need much of the functionality of the Build Decoration, but it leaves the application much more flexible for future great ideas. There is a new `Build Decorator` class called `Collector`, and another class called `Posts`.  The `Collector` provides two Blade directives: `collectitem` and `collectindex`.  The first one will accept a bunch of meta data that gets passed to an implementation of the `Collection` interface.  This interface requires a single method `collect` that should accept the meta data.  The default implementation is `Posts`, but you can specify another one by providing a class name in the `collection_type` key of the meta data passed to the Blade directive.  `Posts` will take the meta data and record it, building up some default values if they are not provided.  The only required key is `title`, which is slugged to create the eventual pretty URL.  This directive will also extract all of the meta data into the symbol table for the scope of the Blade file, so nothing needs to be typed in twice.  The other directive, `collectindex`, simply injects the `Collection` implementation into the Blade file scope as `$collection`.  From there, you can do with it as you will.  If `collectindex` is not given any parameters, it will inject the `Posts` instance by default.

#How do you use it?

In your source directory, you create Blade files that will get processed as normal.  To take advantage of the `Posts` collection and the Build Decoration process, you must do three things: suffix the file with `posts.process.php`, wrap any `@collectindex` directives in `@verbatim` tags, and add the `@decorate` directive to any primary Blade file that will require decoration.  The first thing simply ensures that the proper `File Handler` will process the file.  This is required because the file name must be preserved until the Build Decoration is done.  The normal process will rename the file on the first build.  The second thing will make sure that your directives that use the `Collection` object are hidden from the Blade compiler until there is something to actually use.  The third helps the `File Handler` know when the file is ready to be renamed.

In this repo, checkout the `source` directory.  It looks very similar to a basic Jigsaw `source` directory.  Note the `index.posts.process.php` file.  It contains a `@collectindex` directive and includes another Blade file, `archives`, that also makes use of that directive.  Then look at the `posts` directory.  Here are some sample posts that use the `@collectitem` directive.  Now check out the site in action at http://knots-wall.pubstorm.site/.  You sell the posts were collected and indexed for the front page.  A sidebar was created with some archive links.  And each post was sluggified and saved.
